name: RUN_IN_NODE
on: 
  push:
    branches: ["master"]

concurrency: #* Avoiding concurrent runs.
  group: paiky-lock #* Make sure to also put this in the other workflows
  cancel-in-progress: true

jobs:
  run_in_node_paiky:
      runs-on: ubuntu-latest
      steps:
        - name: "Checkout code" #! Name is optional
          uses: actions/checkout@v4
          
        - name: "Setup Node" #! Name is optional
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
            cache: 'npm' #*Literally  telling github to cache node_modules to speed things up ✨
        #! run: npm install # We don't use this (BUT WE COULD) because it is less performant, amongst other reasons.
        - run: npm ci #$ These are SAME LEVEL as "name" and "uses"
        - run: npm run test
